name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy: 
      matrix:
        os: [windows-latest]
        arch: [x86_64]
        node-version: [14]
        include:
          - os: windows-latest
            arch: i686
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}})
    steps:
    - uses: actions/checkout@master

    - name: Setup VS2019
      if: startsWith(matrix.os, 'windows')
      run: npm install --global --production windows-build-tools
      
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        # Set registry to NPM instead of github packages for publication
        registry-url: 'https://registry.npmjs.org'
        node-version: ${{ matrix.node-version }}
        
    - name: Install Packages
      run: npm i --ignore-scripts
      
    - name: Build
      run: npm run build -- --all --msvs_version=2019
      if: startsWith(github.ref, 'refs/tags/v') != true
      env:
        ARCH: ${{ matrix.arch }}
        
    # Build and publish if version tag is present
    - name: Build & Publish Prebuilds
      run: npm run build:ci -- --msvs_version=2019
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        ARCH: ${{ matrix.arch }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
